version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Istanbul"
  - package-ecosystem: "uv"
    directory: "/e2e"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Istanbul"
